// Generated by Flutter Liquid Glass Shader Tool
// Custom mesh gradient shader for animated backgrounds
import 'dart:ui';

class LiquidShaderPainter {
  // This would be a CustomPainter that uses FragmentProgram
  // for the animated liquid mesh background.
  // In production, we'd load a .frag shader from assets.
  
  static const String shaderPath = 'assets/shaders/liquid_mesh.frag';
  
  // Placeholder until shader compilation pipeline is set up
  static Paint createBackgroundPaint(double animationValue) {
    return Paint()
      ..shader = LinearGradient(
        begin: Alignment.topLeft,
        end: Alignment.bottomRight,
        colors: [
          const Color(0xFF050505),
          const Color(0xFF00F2FE).withOpacity(0.15 + (animationValue % 1.0) * 0.1),
          const Color(0xFF4FACFE).withOpacity(0.10 + (animationValue % 1.0) * 0.08),
          const Color(0xFF00FF87).withOpacity(0.08 + (animationValue % 1.0) * 0.06),
          const Color(0xFF050505),
        ],
        stops: const [0.0, 0.2, 0.5, 0.8, 1.0],
      ).createShader(Rect.fromLTWH(0, 0, 400, 800))
      ..blendMode = BlendMode.srcOver;
  }
}
